# Generated by Django 5.2.9 on 2026-01-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('community', 'Community Member'), ('normal', 'Normal User'), ('doctors', 'Doctors'), ('clincs', 'Clincs')], max_length=20),
        ),
    ]
