# Generated by Django 5.2.9 on 2026-01-19 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_communitymember_community_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitymember',
            options={'verbose_name': 'عضو نقابة', 'verbose_name_plural': 'أعضاء نقابة'},
        ),
        migrations.AlterModelOptions(
            name='normaluser',
            options={'verbose_name': 'مستخدم عادي', 'verbose_name_plural': 'المستخدمين العاديين'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'مستخدم', 'verbose_name_plural': 'المستخدمين'},
        ),
    ]
