# Generated by Django 5.2.9 on 2026-01-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialist',
            options={'verbose_name': 'التخصص', 'verbose_name_plural': 'التخصصات'},
        ),
        migrations.AlterField(
            model_name='specialist',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم التخصص'),
        ),
    ]
