# Generated by Django 5.2.9 on 2026-01-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clincs', '0001_initial'),
        ('specialists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clincs',
            name='Specialist',
            field=models.ManyToManyField(related_name='clincs', to='specialists.specialist'),
        ),
    ]
