# Generated by Django 5.2.9 on 2026-01-19 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clincs', '0003_clincs_user'),
        ('specialists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clincs',
            options={'verbose_name': 'عيادة', 'verbose_name_plural': 'العيادات'},
        ),
        migrations.AlterField(
            model_name='clincs',
            name='Specialist',
            field=models.ManyToManyField(related_name='clincs', to='specialists.specialist', verbose_name='التخصصات'),
        ),
        migrations.AlterField(
            model_name='clincs',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم العيادة'),
        ),
        migrations.AlterField(
            model_name='clincs',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinics', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
