# Generated by Django 5.2.9 on 2026-01-19 08:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clincs', '0004_alter_clincs_options_alter_clincs_specialist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clincs',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='الصورة'),
        ),
    ]
