# Generated by Django 5.2.9 on 2026-01-19 19:39

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialists', '0002_alter_specialist_options_alter_specialist_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المعمل')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='صورة')),
                ('address', models.CharField(max_length=200, verbose_name='العنوان')),
                ('phone', models.CharField(max_length=20, verbose_name='الهاتف')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('rating', models.IntegerField(verbose_name='التقييم')),
                ('specialist', models.ManyToManyField(related_name='hospital', to='specialists.specialist', verbose_name='المستشفى')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مستشفي',
                'verbose_name_plural': 'مستشفيات',
            },
        ),
    ]
