# Generated by Django 5.2.9 on 2026-01-17 12:34

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('phone_number', models.IntegerField(max_length=11)),
                ('license', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('address', models.CharField(max_length=200)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='specialists.specialist')),
            ],
        ),
    ]
