# Generated by Django 5.2.9 on 2026-04-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unregistereddoctor',
            name='allow_online_booking',
            field=models.BooleanField(blank=True, default=False, help_text='Admin approval for online booking', null=True),
        ),
    ]
