# Generated by Django 5.2.9 on 2026-01-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctors_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
