# Generated by Django 5.2.9 on 2026-04-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASER', '0001_initial'),
        ('doctors', '0002_alter_unregistereddoctor_allow_online_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='certificates',
            field=models.ManyToManyField(blank=True, to='ASER.certifications'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='insurance',
            field=models.ManyToManyField(blank=True, to='ASER.insurance'),
        ),
        migrations.AddField(
            model_name='unregistereddoctor',
            name='certificates',
            field=models.ManyToManyField(blank=True, to='ASER.certifications'),
        ),
        migrations.AddField(
            model_name='unregistereddoctor',
            name='insurance',
            field=models.ManyToManyField(blank=True, to='ASER.insurance'),
        ),
    ]
