# Generated by Django 5.2.9 on 2026-01-19 09:51

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctors_phone_number'),
        ('specialists', '0002_alter_specialist_options_alter_specialist_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='address',
            field=models.CharField(max_length=200, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='age',
            field=models.IntegerField(verbose_name='العمر'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='license',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='رخصة العمل'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='name',
            field=models.CharField(max_length=50, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='phone_number',
            field=models.IntegerField(verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='specialists.specialist', verbose_name='التخصص'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
