# Generated by Django 5.2.9 on 2026-04-10 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASER', '0001_initial'),
        ('doctors', '0003_doctor_certificates_doctor_insurance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unregistereddoctor',
            name='about',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ASER.biography'),
        ),
    ]
