# Generated by Django 5.2.9 on 2026-04-16 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASER', '0001_initial'),
        ('doctors', '0004_unregistereddoctor_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='about',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ASER.biography'),
        ),
    ]
