# Generated by Django 5.2.9 on 2026-01-19 10:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_doctors_address_alter_doctors_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='doctor_image',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='صورة الطبيب'),
            preserve_default=False,
        ),
    ]
