# Generated by Django 5.2.9 on 2026-01-19 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_doctors_doctor_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctors',
            options={'verbose_name': 'طبيب', 'verbose_name_plural': ' الأطباء'},
        ),
    ]
