# Generated by Django 5.2.9 on 2026-01-19 12:02

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LapCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='التخصص')),
            ],
            options={
                'verbose_name': 'القسم',
                'verbose_name_plural': 'الاقسام',
            },
        ),
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المعمل')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='صورة')),
                ('address', models.CharField(max_length=200, verbose_name='العنوان')),
                ('phone', models.CharField(max_length=20, verbose_name='الهاتف')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('rating', models.IntegerField(verbose_name='التقييم')),
                ('categories', models.ManyToManyField(related_name='labs', to='labs.lapcategory', verbose_name='الاقسام')),
            ],
            options={
                'verbose_name': 'المعمل',
                'verbose_name_plural': 'المعامل',
            },
        ),
    ]
