# Generated by Django 5.2.9 on 2026-04-13 12:30

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='specialists',
        ),
        migrations.AddField(
            model_name='labspecialists',
            name='lab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='specialists', to='labs.lab'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='labspecialists',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
